logging:
  level:
    root: INFO

spring:
  application:
    name: lectures
  r2dbc:
    driver-class-name: org.mariadb.jdbc.Driver
    url: r2dbc:mariadb://localhost:3306/lecture
    username: root
    password: eddy
  data:
    redis:
      host: localhost
      port: 6379
