logging:
  org:
    springframework:
      web: DEBUG
  level:
    root: INFO

server:
  port: 8081

spring:
  application:
    name: lectures
  r2dbc:
    url: r2dbc:mysql://localhost:3306/lecture
    username: root
    password: eddy
  data:
    redis:
      host: localhost
      port: 6379
